#! /usr/bin/env bash
#
# Author: Jim Anders <jimanders223@gmail.com>

{
# abort on nonzero exitstatus
set -o errexit
# abort on unbound variable
set -o nounset
# don't hide errors within pipes
set -o pipefail

main() {
    # Ask for the administrator password upfront
    sudo -v

        # Keep-alive: update existing `sudo` time stamp until `.macos` has finished
        while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

            if ! [ -x "$(command -v nix-env)" ]; then
                install_nix
            fi

            if ! [ "$(uname)" == "Darwin" ]; then
                if ! [ -x "$(command -v darwin-rebuild)" ]; then
                    install_nix_darwin
                fi

                download_dotfiles
            fi

            darwin-rebuild switch -I darwin-config="${HOME}/src/.files/default.nix"
        }

#{{{ Helper functions
install_nix() {
    local dir
    dir=$(mktemp -d)
    cd "$dir"
    curl -L -o install https://nixos.org/nix/install
    $(command -v sh) install --daemon
    cd "$HOME"
}

install_nix_darwin() {
    local dir
    dir=$(mktemp -d)
    cd "$dir"
    /nix/var/nix/profiles/default/bin/nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer
    ./result/bin/darwin-installer
    cd "$HOME"
}

download_dotfiles() {
    if ! [ -f "$HOME/src/.files" ];then
        mkdir -p "$HOME/src"
        cd "$HOME/src"
        curl https://github.com/janders223/.files/archive/master.tar.gz | tar zx
    fi
}
#}}}

main
}
